version = 1
SPDX-PackageName = "slangroom-chain"
SPDX-PackageSupplier = "Matteo Cristino <matteo@dyne.org>"
SPDX-PackageDownloadLocation = "https://github.com/dyne/slangroom-chain"

[[annotations]]
path = ["test_contracts/**/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Dyne.org foundation"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [".vscode/**/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Dyne.org foundation"
SPDX-License-Identifier = "AGPL-3.0-or-later"
